version: "3.5"

networks:
  alar-network:
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379"
    networks:
      - alar-network

  postgrisql:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=alar
      - POSTGRES_USER=postgres
      - POSTGRES_DB=alar
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d/
    ports:
      - 5436:5432
    networks:
      - alar-network

  backend:
    build:
      context: ../
      dockerfile: ./deploy/backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - alar-network
    depends_on:
      - redis
      - postgrisql

  frontend:
    build:
      context: ../
      dockerfile: ./deploy/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:80
    networks:
      - alar-network

    depends_on:
      - redis
      - postgrisql
      - backend